apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devtube-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:ronsha001/devtube-chart.git
    path: devtube
    targetRevision: HEAD

  destination:
    server: https://kubernetes.default.svc
    namespace: devtube

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true