apiVersion: v1
kind: Service
metadata:
  name: {{ include "devtube.fullname" . }}-api-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ include "devtube.fullname" . }}-api
  {{- if .Values.api.ingress.enabled }}
  type: ClusterIP
  {{- else }}
  type: LoadBalancer
  {{- end}}
  ports:
    - protocol: TCP
      port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
