{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "devtube.fullname" . }}-ingress
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "devtube.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  {{- if .Values.ingress.certificate.enabled }}
  tls:
  - hosts:
    - {{ .Values.ingress.certificate.host }}
  # Change the secret name to ssl-cert-production 
  # for a valid, green certificate in your browser
    secretName: ssl-cert-production
  {{- end }}
  rules:
  - host: {{ .Values.ingress.certificate.host }}
    http:
      paths:
      {{- if .Values.client.ingress.enabled }}
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ include "devtube.fullname" . }}-client-svc
            port: 
              number: {{ .Values.client.port }}
      {{- end}}
      {{- if .Values.api.ingress.enabled }}
      - pathType: Prefix
        path: "/api"
        backend:
          service:
            name: {{ include "devtube.fullname" . }}-api-svc
            port: 
              number: {{ .Values.api.port }}
      {{- end}}
{{- end }}
