apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  mongo_user: {{ .Values.mongodb.auth.rootUser | b64enc }}
  mongo_pw: {{ .Values.mongodb.auth.rootPassword | b64enc }}
  jwt_key: {{ .Values.api.jwt_key | b64enc }}