serviceAccount:
  create: true
  annotations: {}
  name: ""
service:
  type: ClusterIP
  port: 80
namespace: devtube
ingress:
  enabled: true
  certificate:
    enabled: true
    email: ronsh0111@gmail.com
    host: devtube.ddns.net
mongodb:
  architecture: replicaset
  useStatefulSet: true
  replicaCount: 3
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: 1500m
      memory: 1.5Gi
api:
  ingress:
    enabled: true
  image: devtube.azurecr.io/devtube-api
  image_tag: 1.4.1
  jwt_key: "example"
  port: 5000
  resources:
    requests:
      memory: 500Mi
      cpu: 500m
    limits:
      memory: 1.5Gi
      cpu: 1500m
  autoscaling:
    enabled: true
    replicaCount: 2
client:
  ingress:
    enabled: true
  image: devtube.azurecr.io/devtube-app
  image_tag: 1.1.2
  port: 3000
  resources:
    requests:
      memory: 500Mi
      cpu: 500m
    limits:
      memory: 1.5Gi
      cpu: 1500m
  autoscaling:
    enabled: true
    replicaCount: 2
